name: main
on: push
jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7.0.0
      
      - name: param
        run: |
          file="fil1.txt"
          echo "file=$file" >> $GITHUB_ENV
          echo "filepath/$file"
          python main.py --value "$file"
          
      - name: next_Task
        run: |
           echo "$file exist"
  
