name: main
on: push
jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: param
        run: |
          file="fil1.txt"
          echo "file=$file" >> $GITHUB_ENV
          echo "$file"
          
      - name: next_Task
        run: |
           echo "$file exist"
  
